name: JavaBuild
on:
  push:
    paths:
    - '**.java'
    - 'resources/*'
    - '*manifest*'
    - '**build.yml'
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  platformio_package_build:
    name: "Platformio package build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '8'
    - name: "Build platformio jar"
      run: $GITHUB_WORKSPACE/.github/scripts/build_platformio.sh
    - name: "Build arduino jar"
      run:  $GITHUB_WORKSPACE/.github/scripts/build_arduino.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: JarFiles
        path: |
          ESP32PartitionTool-Arduino.zip
          esp32partitiontool-1.0.4-platformio.zip
