name: JavaBuild
on:
  push:
    paths:
    - '**.java'
    - 'resources/*'
    - '*manifest*'
    - '**build.yml'
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  build_packages:
    name: "Platformio package build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '8'
    - name: "Build platformio jar"
      run: $GITHUB_WORKSPACE/.github/scripts/build_platformio.sh
    - name: "Build arduino jar"
      run:  $GITHUB_WORKSPACE/.github/scripts/build_arduino.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: JarFiles
        path: |
          ESP32PartitionTool-Arduino.zip
          esp32partitiontool-platformio.zip

  post_build:
    name: Gather Artefacts
    runs-on: ubuntu-latest
    # wait until jobs are all finished
    needs: build_packages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        # with:
        #   path: builds
      - name: Release check
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ESP32PartitionTool-Arduino.zip
            esp32partitiontool-platformio.zip
